---
# tasks file for roles/nginx

- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "22")


- name: Install apache httpd
  ansible.builtin.apt:
    name: '{{ packagename }}'
    state: present
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "22")

- name: Working with Nginx Templates
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    notify:
    - Restart service nginx

- name: Start service httpd, if not started
  ansible.builtin.service:
    name: '{{ servicename }}'
    state: started

